name: Make New Release
on:
  pull_request:

jobs:
  test-env:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set Env Var
        run: |
          $dir_sha = (Get-FileHash -Path .\hash-source.txt -Algorithm SHA256).Hash
          echo "dir-sha=key-$($dir_sha)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      
      - name: Use Env Var
        run: |
          echo "dir-sha: ${{ env.dir-sha }}"


  test-multiline:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Multiline Var
        run: |
          sha_256=$(shasum -a 256 ./hash-source.txt | cut -d" " -f1)
          sha_384=$(shasum -a 384 ./hash-source.txt | cut -d" " -f1)
          sha_512=$(shasum -a 512 ./hash-source.txt | cut -d" " -f1)

          echo "shas<<EOF" >> $GITHUB_ENV
          echo "$sha_256" >> $GITHUB_ENV
          echo "$sha_384" >> $GITHUB_ENV
          echo "$sha_512" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Use Multiline Var
        run: |
          echo "multiline var: ${{ env.shas }}"


