name: Make New Release
on:
  pull_request:

jobs:
  publish-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set Env Var
        run: |
          $dir_sha = (Get-FileHash -Path .\hash-source.txt -Algorithm SHA256).Hash
          echo "dir-sha=key-$($dir_sha)" >> $GITHUB_ENV
      
      - name: Use Env Var
        run: |
          echo "dir-sha: ${{ env.dir-sha }}"